import type { OrderHistoryItem } from '../../../entities/order-history';

/**
 * Historial de órdenes mock para el panel de agentes.
 *
 * Las órdenes están distribuidas entre los usuarios mock de view-user-profile
 * para que la vista de detalle muestre datos consistentes al filtrar por
 * cualquiera de los tres lados (cliente, repartidor, negocio).
 *
 * TODO(backend): reemplazar por GET /api/support/orders?userType=X&userId=Y.
 * La forma OrderHistoryItem debería mantenerse — si cambia, ajustar este mock.
 */
export const MOCK_ORDER_HISTORY: readonly OrderHistoryItem[] = [
  {
    id: 'ORD-10001',
    placedAt: '2026-04-10T13:20:00.000Z',
    clientId: 'client-101',
    clientName: 'Andrea Figueroa',
    businessId: 'business-301',
    businessName: 'Pupusas Doña Luz',
    courierId: 'courier-201',
    courierName: 'Óscar Bautista',
    total: 235,
    currency: 'HNL',
    status: 'DELIVERED',
  },
  {
    id: 'ORD-10002',
    placedAt: '2026-04-11T19:45:00.000Z',
    clientId: 'client-101',
    clientName: 'Andrea Figueroa',
    businessId: 'business-302',
    businessName: 'Burger Master Tegus',
    courierId: 'courier-202',
    courierName: 'Keyla Mejía',
    total: 410,
    currency: 'HNL',
    status: 'DELIVERED',
  },
  {
    id: 'ORD-10003',
    placedAt: '2026-04-13T12:05:00.000Z',
    clientId: 'client-101',
    clientName: 'Andrea Figueroa',
    businessId: 'business-303',
    businessName: 'Café Renacer',
    courierId: null,
    courierName: null,
    total: 98,
    currency: 'HNL',
    status: 'CANCELLED',
  },
  {
    id: 'ORD-10004',
    placedAt: '2026-04-09T11:00:00.000Z',
    clientId: 'client-102',
    clientName: 'Luis Fernando Paz',
    businessId: 'business-301',
    businessName: 'Pupusas Doña Luz',
    courierId: 'courier-201',
    courierName: 'Óscar Bautista',
    total: 190,
    currency: 'HNL',
    status: 'DELIVERED',
  },
  {
    id: 'ORD-10005',
    placedAt: '2026-04-14T10:30:00.000Z',
    clientId: 'client-102',
    clientName: 'Luis Fernando Paz',
    businessId: 'business-302',
    businessName: 'Burger Master Tegus',
    courierId: 'courier-202',
    courierName: 'Keyla Mejía',
    total: 325,
    currency: 'HNL',
    status: 'IN_PROGRESS',
  },
  {
    id: 'ORD-10006',
    placedAt: '2026-04-08T20:15:00.000Z',
    clientId: 'client-103',
    clientName: 'Gabriela Midence',
    businessId: 'business-303',
    businessName: 'Café Renacer',
    courierId: 'courier-203',
    courierName: 'Julio César Díaz',
    total: 145,
    currency: 'HNL',
    status: 'REFUNDED',
  },
  {
    id: 'ORD-10007',
    placedAt: '2026-04-12T14:00:00.000Z',
    clientId: 'client-103',
    clientName: 'Gabriela Midence',
    businessId: 'business-301',
    businessName: 'Pupusas Doña Luz',
    courierId: 'courier-201',
    courierName: 'Óscar Bautista',
    total: 275,
    currency: 'HNL',
    status: 'DELIVERED',
  },
  {
    id: 'ORD-10008',
    placedAt: '2026-04-13T18:30:00.000Z',
    clientId: 'client-102',
    clientName: 'Luis Fernando Paz',
    businessId: 'business-301',
    businessName: 'Pupusas Doña Luz',
    courierId: 'courier-201',
    courierName: 'Óscar Bautista',
    total: 210,
    currency: 'HNL',
    status: 'DELIVERED',
  },
  {
    id: 'ORD-10009',
    placedAt: '2026-04-07T17:10:00.000Z',
    clientId: 'client-101',
    clientName: 'Andrea Figueroa',
    businessId: 'business-302',
    businessName: 'Burger Master Tegus',
    courierId: 'courier-203',
    courierName: 'Julio César Díaz',
    total: 380,
    currency: 'HNL',
    status: 'DELIVERED',
  },
  {
    id: 'ORD-10010',
    placedAt: '2026-04-06T09:45:00.000Z',
    clientId: 'client-103',
    clientName: 'Gabriela Midence',
    businessId: 'business-302',
    businessName: 'Burger Master Tegus',
    courierId: 'courier-202',
    courierName: 'Keyla Mejía',
    total: 295,
    currency: 'HNL',
    status: 'DELIVERED',
  },
  {
    id: 'ORD-10011',
    placedAt: '2026-04-11T13:00:00.000Z',
    clientId: 'client-102',
    clientName: 'Luis Fernando Paz',
    businessId: 'business-303',
    businessName: 'Café Renacer',
    courierId: 'courier-202',
    courierName: 'Keyla Mejía',
    total: 165,
    currency: 'HNL',
    status: 'DELIVERED',
  },
  {
    id: 'ORD-10012',
    placedAt: '2026-04-14T09:00:00.000Z',
    clientId: 'client-101',
    clientName: 'Andrea Figueroa',
    businessId: 'business-303',
    businessName: 'Café Renacer',
    courierId: 'courier-203',
    courierName: 'Julio César Díaz',
    total: 220,
    currency: 'HNL',
    status: 'IN_PROGRESS',
  },
  {
    id: 'ORD-10013',
    placedAt: '2026-04-05T20:45:00.000Z',
    clientId: 'client-103',
    clientName: 'Gabriela Midence',
    businessId: 'business-301',
    businessName: 'Pupusas Doña Luz',
    courierId: 'courier-201',
    courierName: 'Óscar Bautista',
    total: 180,
    currency: 'HNL',
    status: 'CANCELLED',
  },
  {
    id: 'ORD-10014',
    placedAt: '2026-04-10T19:00:00.000Z',
    clientId: 'client-102',
    clientName: 'Luis Fernando Paz',
    businessId: 'business-302',
    businessName: 'Burger Master Tegus',
    courierId: 'courier-201',
    courierName: 'Óscar Bautista',
    total: 360,
    currency: 'HNL',
    status: 'DELIVERED',
  },
  {
    id: 'ORD-10015',
    placedAt: '2026-04-12T11:30:00.000Z',
    clientId: 'client-101',
    clientName: 'Andrea Figueroa',
    businessId: 'business-301',
    businessName: 'Pupusas Doña Luz',
    courierId: 'courier-202',
    courierName: 'Keyla Mejía',
    total: 205,
    currency: 'HNL',
    status: 'DELIVERED',
  },
];
